### ISSUE TITLE
option to launch inter protocol contracts after bootstrap

### ISSUE THREAD

**Issue by dckc** [Agoric/instagoric#1]
Instagoric currently runs the proposals to start the Inter Protocol contracts as part of chain bootstrap:

https://github.com/Agoric/instagoric/blob/e9b4172c10fbe4666d65cd9057a17118b5287573/bases/shared/entrypoint.sh#L358-L359

In the April / May [Runbook: RUN Protocol Preview](https://github.com/Agoric/agoric-sdk/wiki/Runbook%3A-RUN-Protocol-Preview), we bootstrapped the chain first and then seprately launched the contracts as a consequence of a governance vote. https://github.com/Agoric/agoric-sdk/issues/5819#issuecomment-1198190191 notes that running them separately like that is not something we do often; in particular, instagoric doesn't do it. Given that we aim to do them separately in production, instagoric should support it.

**Comment by ivanlei** [comment]
Based on the efforts completed in https://github.com/Agoric/agoric-sdk/issues/6957 this is no longer necessary.
